### ISSUE TITLE
Deprecate the misspelt properties 'testng.slave.adpter'

### ISSUE THREAD

**Issue by missedone** [testng-team/testng-remote#16]
when using distributed testng in slave mode,
in `SuiteSlave.java`:
```java
public static final String SLAVE_ADPATER = "testng.slave.adpter";
```
should be:
```java
public static final String SLAVE_ADAPTER = "testng.slave.adapter";
```

**Comment by juherr** [comment]
Already done on my computer. I will rebase the commit and propose it asap.

**Comment by juherr** [comment]
Related to https://github.com/testng-team/testng-distributed
