### ISSUE TITLE
Faild to running test on TestNG version 7.10.0

### ISSUE THREAD

**Issue by bobshie** [testng-team/testng-remote#186]
Eclipse running log:
[RemoteTestNG] failed to get TestNG version from class: java.lang.IllegalArgumentException: invalid version "[WORKING]": non-numeric "[WORKING]"
[RemoteTestNG] now trying to parse the version from pom.properties
[RemoteTestNG] parsing TestNG version at jar:file:1.jar!/META-INF/maven/org.testng/testng/pom.properties
[RemoteTestNG] detected TestNG version 7.10.0
Exception in thread "main" java.lang.NoSuchFieldError: port
        at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:69)

Console log:
java.lang.NullPointerException
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at org.testng.remote.strprotocol.JsonMessageSender.receiveMessage(JsonMessageSender.java:63)
        at org.testng.remote.strprotocol.MessageHub.receiveMessage(MessageHub.java:51)
        at org.testng.remote.strprotocol.AbstractRemoteTestRunnerClient$ServerConnection.run(AbstractRemoteTestRunnerClient.java:179)

**Comment by juherr** [comment]
@bobshie Could you try with 7.10.1 which was released today?

@krmahadevan fyi

**Comment by krmahadevan** [comment]
@juherr - I think this will need some changes at the eclipse plugin level perhaps? @missedone - Can you please help take a look ?

**Comment by missedone** [comment]
@bobshie what's the testng eclipse plugin version did you use? i just tried with the last plugin and latest testing 7.10.0 and 7.10.1 without issue.

**Comment by bobshie** [comment]
the version of plugin is:
TestNG            7.9.0.202312310355 org.testng.eclipse.feature.group 
TestNG P2 Feature 7.9.0.r202312310341 org.testng.p2.feature.feature.group TestNG Team

I tested, there is the same issue on 7.10.1.

**Comment by bobshie** [comment]
the related change is: 
https://github.com/testng-team/testng/commit/94bf0111c9f721d788db21670edb352cc5fe044f


![image](https://github.com/testng-team/testng-remote/assets/107839174/e4684507-26a0-4383-860a-84a7e932eadf)

**Comment by missedone** [comment]
@bobshie could you copy the content here for troubleshooting?
<img width="1511" alt="image" src="https://github.com/testng-team/testng-remote/assets/555134/4283c07c-6e03-481e-a22d-7a3bc617fa87">

**Comment by bobshie** [comment]
$ cat testng2-err.txt

eclipse.buildId=I20230902-1200.202309151353
java.version=17.0.6
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /home/tester/workspace/maven-workspace

org.testng.eclipse
Info
Thu Apr 11 17:18:24 CST 2024
[TestNGLaunchConfigurationDelegate] Launching:
  Classpath: /repo/tester/.eclipse/org.eclipse.platform_4.29.0_324915089_linux_gtk_x86_64/configuration/org.eclipse.osgi/432/0/.cp/lib/testng-remote.jar /home/tester/testng-demo/target/test-classes /home/tester/testng-demo/target/classes /repo/tester/.m2/repository/org/testng/testng/7.10.1/testng-7.10.1.jar /repo/tester/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar /repo/tester/.m2/repository/com/beust/jcommander/1.82/jcommander-1.82.jar /repo/tester/.m2/repository/org/webjars/jquery/3.7.1/jquery-3.7.1.jar
  VMArgs:    -ea
  Class:     org.testng.remote.RemoteTestNG
  Args:      -serport 43579 -protocol json -d /home/tester/testng-demo/test-output /home/tester/testng-demo/src/main/resources/suites/demo/test-demo2.xml
java -ea -classpath /repo/tester/.eclipse/org.eclipse.platform_4.29.0_324915089_linux_gtk_x86_64/configuration/org.eclipse.osgi/432/0/.cp/lib/testng-remote.jar:/home/tester/testng-demo/target/test-classes:/home/tester/testng-demo/target/classes:/repo/tester/.m2/repository/org/testng/testng/7.10.1/testng-7.10.1.jar:/repo/tester/.m2/repository/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/repo/tester/.m2/repository/com/beust/jcommander/1.82/jcommander-1.82.jar:/repo/tester/.m2/repository/org/webjars/jquery/3.7.1/jquery-3.7.1.jar org.testng.remote.RemoteTestNG -serport 43579 -protocol json -d /home/tester/testng-demo/test-output /home/tester/testng-demo/src/main/resources/suites/demo/test-demo2.xml



eclipse.buildId=I20230902-1200.202309151353
java.version=17.0.6
java.vendor=Azul Systems, Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64 -data /home/tester/workspace/maven-workspace

=============

[RemoteTestNG] detected TestNG version 7.10.1
Exception in thread "main" java.lang.NoSuchFieldError: port
        at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:69)

**Comment by bobshie** [comment]
TestNG 7.9.0.202312310355  is based on testng-remote 1.6.0

https://github.com/testng-team/testng-eclipse/releases/tag/7.9.0.202312310355

there is "69: if (cla.port != null && ra.serPort != null) {" in testng-remote 1.6.0.
but it's deleted in the latest version of testng-remote.

**Comment by bobshie** [comment]
I build a latest testng-remote and use it to load TestNG 7.10.1, there is error: 

7.10.1 is not a supported TestNG Version. 
   getFirst(ServiceLoadHelper.java:31). 

I checked the testng-remote code, it's need to add RemoteTestNG7_10  and RemoteTestNGFactory7_10.  and release the version.

**Comment by juherr** [comment]
Pull requests are welcome and are the best way to have quick fixes.

**Comment by missedone** [comment]
@bobshie @juherr the issue actually was fixed in PR https://github.com/testng-team/testng-remote/pull/175, will release 1.7.0 soon

**Comment by missedone** [comment]
@bobshie thanks for looking into this issue, the new release of testng eclipse plugin of 7.10 will be release in few hours

**Comment by bobshie** [comment]
@missedone , Hello Nick, I tested with the latest testng-remote-dist-1.8.0-SNAPSHOT-shaded, it works well. very thanks.

**Comment by missedone** [comment]
@bobshie , better to use the release version `1.7.0`

```
<dependency>
  <groupId>org.testng.testng-remote</groupId>
  <artifactId>testng-remote-dist</artifactId>
  <version>1.7.0</version>
  <classifier>shaded</classifier>
</dependency>
```
