### ISSUE TITLE
Should we support older versions?

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-remote#33]
Related: https://groups.google.com/forum/#!topic/testng-users/BIXTqsZeTuI

**Comment by missedone** [comment]
The problem I can see now is, AbstractRemoteTestNG implements IResultListener2 which is not available in testng 6.0.
One solution is to add a copy of IResultListener2, however, I think it'd introduce more trouble than gain.

**Comment by missedone** [comment]
OK, looks like I figured out a way, will push it after more test.

**Comment by juherr** [comment]
Awesome! :+1:
