### ISSUE TITLE
1.3.0 not available in jcenter

### ISSUE THREAD

**Issue by johnsdouglass** [testng-team/testng-remote#55]
1.3.0 is the latest release version per the README, but 1.2.1 is the latest version in jcenter.

**Comment by missedone** [comment]
@johnsdouglass , the release is on Bintray, I did release 1.3.0 as usual, not sure why 1.3.0 not on JCenter.

https://bintray.com/testng-team/testng/testng-remote

you can use the repository at the moment:
```xml
<repositories>
                <repository>
                    <snapshots>
                        <enabled>false</enabled>
                    </snapshots>
                    <id>bintray-testng-team-testng</id>
                    <name>bintray</name>
                    <url>https://dl.bintray.com/testng-team/testng</url>
                </repository>
            </repositories>
```

**Comment by johnsdouglass** [comment]
Thanks. That repository works for me.
