### ISSUE TITLE
Add integration tests...

### ISSUE THREAD

**Issue by juherr** [testng-team/testng-remote#7]
... which should test against different testng versions (at least 6.5.1, 6.9.8 and 6.9.10)

@missedone I'm open to write some of them, but could you describe some test cases?

**Comment by juherr** [comment]
+ add travis and co

**Comment by missedone** [comment]
right, please give me some time to think about the test cases.
in general, the tests will cover 1) message payload inter-communication with different protocol (especially for json), 2) versioned RemoteTestNG should work properly with the corresponding testng and new feature introduced by testng is supported by RemoteTestNG as well, etc.

**Comment by juherr** [comment]
See https://github.com/testng-team/testng-remote/pull/17#issuecomment-172790319

**Comment by missedone** [comment]
though this is still working in progress, would like to share the idea first.
I'm going to verify testng-remote with groovy to be benefit with its running as go without compiling.
there will be two groovy script:
1. the entry script the will iterate over all release versions of testng, 
and 2. the test case script running the actual test

here is [the sample test case script](https://github.com/testng-team/testng-remote/blob/1e7544ed32f6f5c86994f27f265c5293d64bd0d8/remote-test/src/main/groovy/TestNGTest.groovy#L1), the first line of it `@Grab('org.testng:testng:6.9.10')` is supposed to be edited by the entry script (with substituting the version with the one in the for-loop)

**Comment by juherr** [comment]
Awesome ! Great idea ! :+1:

But why `src/main` instead of `src/test` ?
